### ISSUE TITLE
KerasSequenceLoader on GCP and `Unsupported .version 7.6; current version is '7.4'`

### ISSUE THREAD

**Issue by zygm0nt** [GoogleCloudPlatform/nvidia-merlin-on-vertex-ai#27]
**How to use `KerasSequenceLoader` on a GCP instance?**

I'm training my model on AI Platform in GCP, where I submit my code as a docker container. The code has been tested on a spawned VM instance where it runs properly.
However when running it on AI Platform I'm getting errors like:

```
ptxas application ptx input, line 9; fatal   : Unsupported .version 7.6; current version is '7.4'
```
This actually comes from `numba` and is related to a mismatch between version of the drivers vs package installed (at least that's how I understand this).

I've tried using different images as a base but it actually does not help much the version in image is still too high (either 7.6 or 7.7, depending on the image). So, is there a way to run my code properly and reliably on GCP AI Platform?

Perhaps I should use some older version of the image that would have older package installed, but if so - which version would that be?

I've been trying to run the following base images:
* `nvcr.io/nvidia/merlin/merlin-tensorflow:22.11`
* `nvcr.io/nvidia/merlin/merlin-training:22.05` - this one is used here: https://github.com/GoogleCloudPlatform/nvidia-merlin-on-vertex-ai

Both failed.

*Note*: Here's a way to solve it when having access to the machine: https://github.com/numba/numba/issues/7006

**Comment by leiterenato** [comment]
Hi @zygm0nt 
How did you create your Dockerfile?
Can you provide the file so I can take a look at?

Did you use one of the Dockerfiles defined here?
https://github.com/GoogleCloudPlatform/nvidia-merlin-on-vertex-ai/tree/main/src

**Comment by zygm0nt** [comment]
I've tried using the base image defined in https://github.com/GoogleCloudPlatform/nvidia-merlin-on-vertex-ai/blob/main/src/Dockerfile.nvtabular but it does not help. There's still this conflict from numba.

I'm getting the following output from numba:
```
root@4421393f76be:/opt/tritonserver# numba -s | grep CUDA
__CUDA Information__
CUDA Device Initialized                       : True
CUDA Driver Version                           : 11.5
CUDA Runtime Version                          : 11.7
CUDA NVIDIA Bindings Available                : True
CUDA NVIDIA Bindings In Use                   : False
```

And the crucial part here is the mismatch between `CUDA driver version` and `CUDA Runtime Version`. Seems they should be the same for the numba to work correctly. 

My `Dockerfile` looks something like this:

```
FROM nvcr.io/nvidia/merlin/merlin-tensorflow:22.11 as merlin-base

# Copy and install python requirements
COPY requirements-nvt.txt requirements.txt
RUN pip install --no-cache-dir -U pip
RUN pip install --no-cache-dir -r requirements.txt
```

Nothing really fancy. My `requirements.txt` actually just installs some project specific things, nothing related to CUDA drivers, nothing breaking tensorflow dependencies, or similar.

**Comment by leiterenato** [comment]
Is this the output of a Vertex AI Training job interactive shell?

Did you try to export the ENVs explicitly in the Dockerfile?
```
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/compat/lib.real:/usr/local/hugectr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/lib:/repos/dist/lib
```

In this particular solution (this repo) I am using HugeCTR and the hugectr.DataReaderParams.
https://github.com/GoogleCloudPlatform/nvidia-merlin-on-vertex-ai/blob/7489a4e6561d0b2d8dcc096e692b35672e04250f/src/training/hugectr/model.py#L49

I haven't extensively tested the KerasSequenceLoader, but from my experience this driver compatibility can be an issue.
What I would try is to use older versions of the nvidia base image.

Let me know if you had any progress.

**Comment by leiterenato** [comment]
For you particular case, to be more precise, you can create a Vertex AI Training Job with interactive shell enabled.
https://cloud.google.com/vertex-ai/docs/training/monitor-debug-interactive-shell#vertexai_enable_web_access-api

In you code, include a sleep so you can enter the shell and check the nvidia drivers (nvidia-smi).

**Comment by zygm0nt** [comment]
Thanks for the tip. I've enabled web access and via interactive shell I've checked cuda drivers. They seem in sync. 
The output of `numba -s | grep CUDA` gives me the following output:

```
CUDA Driver Version                           : (11, 6)                                                                                                                                                                                                                                                        
CUDA Runtime Version                          : 11060
```
Which according to https://github.com/numba/numba/issues/7006 is a correct behavior. 

Nevertheless, the error still persists.

I've tried adding the `ENV` setting you've posted above, but that does not solve the problem.

**Comment by zygm0nt** [comment]
Problem solved - it was caused by the docker image script not being used. When running the container image with the following config it failed:


```
workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-16
    acceleratorType: NVIDIA_TESLA_P100
    acceleratorCount: 2
  replicaCount: 1
  containerSpec:
    imageUri: docker-image
    command:
    -  my-training-endpoint
    args:
      -  args...
```

But adding `/opt/nvidia/nvidia_entrypoint.sh` as a runner helped:

```
workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-16
    acceleratorType: NVIDIA_TESLA_P100
    acceleratorCount: 2
  replicaCount: 1
  containerSpec:
    imageUri: docker-image
    command:
    -  /opt/nvidia/nvidia_entrypoint.sh
    args:
      - my-training-endpoint
      -  args...
```
